apiVersion: v1
kind: Pod
metadata:
  name: privileged-centos
  namespace: default
  labels:
    app: centos
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  - name: privileged-centos
    image: centos:6.8
    imagePullPolicy: IfNotPresent
    command: ["top","-b"]  
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker
      mountPath: /usr/bin/docker
  volumes:
      - name: docker
        hostPath:
          path: /usr/bin/docker
          type: File

