allinone:
    pid: host
    image: neuvector/allinone:5.0.0
    container_name: allinone_5.0.0
    privileged: true
    environment:
        - CLUSTER_JOIN_ADDR=192.168.101.97
        - NV_PLATFORM_INFO=platform=Docker
        - ENV_CTRL_PATH_DEBUG=true
    ports:
        - 18300:18300
        - 18301:18301
        - 18400:18400
        - 18401:18401
        - 18301:18301/udp
        - 8443:8443
    volumes:
        - /lib/modules:/lib/modules:ro
        - /var/neuvector:/var/neuvector
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc:/host/proc:ro
        - /sys/fs/cgroup:/host/cgroup:ro
        - /root/neuvector_5.0.0/bin:/usr/local/bin
        - /usr/local/go_1.16.15:/usr/local/go
