allinone:
    pid: host
    image: neuvector/allinone:haolp_5.0.0
    container_name: allinone_haolp_5.0.0
    privileged: true
    environment:
        - CLUSTER_JOIN_ADDR=10.240.19.222
        - NV_PLATFORM_INFO=platform=Docker
        - ENV_CTRL_PATH_DEBUG=true
    ports:
        - 18300:18300
        - 18301:18301
        - 18400:18400
        - 18401:18401
        - 18301:18301/udp
        - 8443:8443
    environment:
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/work/goProject/bin:/usr/local/go/bin:/home/work/goProject/bin
        - GOPATH=/home/work/goProject
        - GO111MODULE=on
        - GOPROXY=https://goproxy.cn
    volumes:
        - /lib/modules:/lib/modules:ro
        - /var/neuvector:/var/neuvector
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc:/host/proc:ro
        - /sys/fs/cgroup:/host/cgroup:ro
        - /root/neuvector_5.0.0/bin:/usr/local/bin
        - /usr/local/go:/usr/local/go
